#! /bin/sh


echo "============================================================"
echo "=                 Generate a dictionary for                ="
echo "============================================================"


#cd ${PWD}/src/

if [ -e ${PWD}/src/rootdict.cc ]; then
    echo "The file rootdict.cc is allrady exist .."
    rm ${PWD}/src/rootdict.*
    rootcint ${PWD}/src/rootdict.cc -c ${PWD}/include/TCaloHitRoot.hh ${PWD}/include/TRawCaloHitRoot.hh
else
    echo "Create a new dictionary rootdict.cc .."
    rootcint ${PWD}/src/rootdict.cc -c ${PWD}/include/TCaloHitRoot.hh ${PWD}/include/TRawCaloHitRoot.hh

fi

ls -lthr ${PWD}/src/

echo "============================================================"




